### ISSUE TITLE
Ejabberd http not working with tls since last commits

### ISSUE THREAD

**Issue by OscarDev-** [processone/tls#12]
Hi all,

I've been trying to compile ejabberd in my local CentOs 7 machine, the build runs fine, but when I try to use ejabberd_http with tls (like the admin console or websockets) the connection is terminated.
I get the following entry in the crash.log:

2015-05-28 09:14:14 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.459.0>
    registered_name: []
    exception error: {{case_clause,<<2>>},[{p1_tls,recv,3,[{file,"src/p1_tls.erl"},{line,171}]},{ejabberd_http,receive_headers,1,[{file,"src/ejabberd_http.erl"},{line,185}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.6932>,<0.312.0>,#Port<0.6931>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 1376
  neighbours:
2015-05-28 09:14:14 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {case_clause,<<2>>}
     Offender:   [{pid,<0.459.0>},{name,undefined},{mfargs,{ejabberd_http,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

When I revert the p1_tls dep. to commit e231cbde546c2e2200f6dae01d13cf743d253c6d it is working fine.

**Comment by alexeyshch** [comment]
Thanks for the report, it should be fixed now.
